### ISSUE TITLE
Does anyone want Windows support?

### ISSUE THREAD

**Issue by dmitshur** [goxjs/gl#1]
Right now this package supports OS X, Linux, and browsers.

Windows is currently not supported. I can add it very easily, it would take me an hour or so, but I wouldn't want to spend time on it unless people actually want/need it (I don't use Windows myself).

If you're using this package (or considering it) and want Windows backend added, just leave a +1 here.

**Comment by joeblew99** [comment]
+1 :)

this is a great project.

**Comment by dmitshur** [comment]
Thanks! Are you using Windows primarily, so you couldn't use this package until this is resolved? Or is the +1 a general wish?

**Comment by joeblew99** [comment]
I use osx, Linus and windows.
I develop opengl software for a living
