### ISSUE TITLE
Getting an error in go 1.5

### ISSUE THREAD

**Issue by ghost** [goxjs/gl#11]
When I try this `go get -u github.com/goxjs/gl/...` I get this error

```
package golang.org/x/mobile/event/config: cannot find package "golang.org/x/mobile/event/config" in any of:
    /usr/local/go/src/golang.org/x/mobile/event/config (from $GOROOT)
```

this maybe because of the this refactor in this commit,
https://github.com/golang/mobile/commit/f632204bccc633bc945896a2aacb959dbc53f859

**Comment by dmitshur** [comment]
That error was only in the `github.com/goxjs/gl/tests` package.

You're right, it's because of that refactor in https://github.com/golang/mobile/commit/f632204bccc633bc945896a2aacb959dbc53f859.

Thank you for reporting, I'll fix this now.
