### ISSUE TITLE
headless

### ISSUE THREAD

**Issue by ghost** [goxjs/gl#12]
any plans to support headless gl ?

**Comment by dmitshur** [comment]
What kind of headless GL did you have in mind? Can you provide examples of environments you're considering?

**Comment by ghost** [comment]
linux server side.
I want to try this so that i can try rending out to disk.

**Comment by dmitshur** [comment]
I don't have immediate plans to work on supporting this, but it seems like a good thing to have, if it's possible.

Do you have some links to resources for what it'd take to support this?

This has to do with OpenGL context creation and not with the OpenGL bindings. However, this package is currently not responsible for OpenGL context creation. It only associates the bindings with the context that was created and made active.

The glfw package is responsible for creating a window, context creation and getting input. I think that's where this feature would go. It might also go into a separate package that's like glfw, but doesn't create a window.

**Comment by ghost** [comment]
https://github.com/go-gl/glfw/search?utf8=%E2%9C%93&q=headless

Seems it support headless on OSX at least :)

**Comment by dmitshur** [comment]
I'm not sure that it supports headless rendering. It does support a limited mode where you can use its other features, like timers, etc. At least according to https://github.com/glfw/glfw/issues/482#issuecomment-87346481.

I'll ask again because I couldn't find an answer in the FAQ nor docs. See https://github.com/glfw/glfw/issues/648.

**Comment by ghost** [comment]
Getting it working wth a hidden window (as they mention), would be ok.
Obviously better without but well thats how it is.

**Comment by dmitshur** [comment]
In that case, you should be able to do that with goxjs/gl and goxjs/glfw, as described at:

http://www.glfw.org/docs/latest/context.html#context_offscreen

I haven't tried it yet, so let me know if something's missing.

**Comment by ghost** [comment]
awesome. Will give it a crack and get back to you if i hit any blockers
