### ISSUE TITLE
JS TexImage2D produces TypeError

### ISSUE THREAD

**Issue by nytehauq** [goxjs/gl#18]
`TypeError: Argument 9 of WebGLRenderingContext.texImage2D does not implement interface ArrayBufferViewOrNull` on Firefox 42.0 and `Uncaught TypeError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': parameter 9 is not of type 'ArrayBufferView'` on Chrome 48.0.2564.109.

AFAIK the `data` parameter of `gl.TexImage2D` is a `[]byte` which becomes a `Uint8Array` in GopherJS... which should satisfy the [WebGL standard](https://www.khronos.org/registry/webgl/specs/1.0/#TEXIMAGE2D) which calls for an [ArrayBufferView](https://developer.mozilla.org/en-US/docs/Web/API/ArrayBufferView).

For comparison, `gl.BufferData` takes a `[]byte` and works fine. The only difference I can see is that the WebGL spec for `bufferData` specifies a `BufferDataSource?` (which is defined as an `ArrayBufferView` or an `ArrayBuffer` in the spec) and not an `ArrayBufferView?` type for the data parameter.

**Comment by dmitshur** [comment]
Thanks for reporting.

> AFAIK the `data` parameter of `gl.TexImage2D` is a `[]byte` which becomes a `Uint8Array` in GopherJS... which should satisfy the [WebGL standard](https://www.khronos.org/registry/webgl/specs/1.0/#TEXIMAGE2D) which calls for an [ArrayBufferView](https://developer.mozilla.org/en-US/docs/Web/API/ArrayBufferView).

Yeah, that sounds right.

Have you tried it in other browsers, like Chrome?

Can you post your usage code?

I certainly use and rely on that func in my projects and I haven't had such issues. For example, see [here](https://github.com/shurcooL/Hover/blob/4e3a75db050058453b760c7b9b617f1b0302f065/main.go#L307) for one usage example.

**Comment by nytehauq** [comment]
Thanks for all the work!

Chrome also throws a TypeError. Even [this code (gist)](https://gist.github.com/nytehauq/895c4f71dae02eb6bf15) produces the error.  Grabbed the latest `gopherjs/gopherjs`, `goxjs/gl`, and `goxjs/glfw` just now and the result is the same. Doesn't seem to matter what `format` is specified or whether `nil` or `[]byte{}` or `someByteSlice=[]byte{}` are passed as `data`.

Oh wow. This works:

`gl.TexImage2D(gl.TEXTURE_2D, 0, 10, 10, gl.RGBA, gl.UNSIGNED_BYTE, []byte{0})`

These do not:

`gl.TexImage2D(gl.TEXTURE_2D, 0, 10, 10, gl.RGBA, gl.UNSIGNED_BYTE, []byte{})`
`gl.TexImage2D(gl.TEXTURE_2D, 0, 10, 10, gl.RGBA, gl.UNSIGNED_BYTE, nil)`

Seems that GopherJS's nil/empty slices are not `ArrayBuffers` nor are they `null`. For reference, all three cases work on Native.

**Comment by dmitshur** [comment]
An orthogonal question, but is it valid to call `gl.TexImage2D` with a `nil` data? In what situations would one want to do that?

**Comment by dmitshur** [comment]
From https://www.khronos.org/registry/webgl/specs/1.0/#TEXIMAGE2D:

> If pixels is null, a buffer of sufficient size initialized to 0 is passed.

So it appears to be a valid operation.

**Comment by dmitshur** [comment]
Thanks again for reporting this issue @nytehauq. It should be fixed in ceadefa35a871d0e3d85a25f2d3796400fbf0678 now. Please let me know if you notice anything else.

**Comment by nytehauq** [comment]
Great, thanks for the quick fix. Passing a `nil` data is useful for fullscreen renderbuffer textures for color-based picking (or any situation where you're going to be rendering to a texture that begins empty). As an aside, `ReadPixels` works for at least this limited use-case.
