### ISSUE TITLE
WebGL GetIntegerv: not yet tested [Confirmed Functional]

### ISSUE THREAD

**Issue by tanema** [goxjs/gl#19]
Wanted to give some feedback that this seems to be functional. I will probably be confirming a few more of these over the next few days.

``` golang
gl.GetIntegerv(gl.VIEWPORT, viewport)
```

returns `[0 0 300 150]` and I checked my context and it says `WebGLRenderingContext {canvas: canvas, drawingBufferWidth: 300, drawingBufferHeight: 150}`

**Comment by dmitshur** [comment]
Awesome!

Feel free to make PRs to remove those warning as soon as you see them and confirm the func works as expected, and I'll merge them.

The warnings are only there to let you know the func hasn't yet been used in the real world, but I expect them all to be correct and function well. It's just in the off-chance something doesn't work, you'll know why that's the case.

**Comment by tanema** [comment]
Okay I will create a pull request when I have finished testing all the items that my code touches. Cheers!
