### ISSUE TITLE
Can't get second attribute location

### ISSUE THREAD

**Issue by bombjackm** [goxjs/gl#24]
Hi,
I took the triangle example and just added the lines bellow:
...
attribute vec3 aVertexPosition;
**attribute vec3 aVertexPosition2;**
...
vertexPositionAttrib := gl.GetAttribLocation(program, "aVertexPosition")
**fmt.Printf("vertexPositionAttrib = %d", vertexPositionAttrib)
vertexPositionAttrib2 := gl.GetAttribLocation(program, "aVertexPosition2")
fmt.Printf("vertexPositionAttrib2 = %d", vertexPositionAttrib2)**
...

I build it with gopherjs and the value of vertexPositionAttrib2 is -1.

Did I missed something?

Regards,

Marc

**Comment by dmitshur** [comment]
That looks correct to me, I'd expect it to work.

I'll try to reproduce.

**Comment by dmitshur** [comment]
I could reproduce. I think it's because `aVertexPosition2` is unused in your shader code, so it gets optimized away.

Try actually using it in the shader, then it works fine:

```
gl_Position = uPMatrix * uMVMatrix * vec4(aVertexPosition, 1.0) * vec4(aVertexPosition2, 1.0);
```

**Comment by bombjackm** [comment]
Thanks a lot. It works now :)

**Comment by bombjackm** [comment]
Thanks al lot for your help

2017-03-20 17:28 GMT+01:00 Dmitri Shuralyov <notifications@github.com>:
