### ISSUE TITLE
Question about go version 

### ISSUE THREAD

**Issue by joeblew99** [goxjs/gl#3]
I presume this needs go 1.5 since its using gomobile ?

**Comment by dmitshur** [comment]
This package will work on OS X, Linux and in browsers with latest stable version (Go 1.4.2) or later.

For compiling and deploying iOS and Android programs, you will likely need Go 1.5.

**Comment by joeblew99** [comment]
Wow thats really fantastic.

Will try all of them this afternoon.

I guess they I'll one day be merged.

I noticed when I was trying the e samples for opengl on android nexus 6 I was only getting about 30 to 40 fps for very simple example.
The loop is redrawing everything each time I guess.
I am thinking of using a merkle tree or day to allow speed up
