### ISSUE TITLE
Complete implementation of all remaining functions.

### ISSUE THREAD

**Issue by dmitshur** [goxjs/gl#4]
Both the WebGL and Windows backends (`glweb.gl` and `gl_windows.go`) are partially implemented. Most common funcs are there (for all my tests and gxui tests), but far from all.

All remaining funcs are marked with "not yet implemented" panics.

**Comment by dmitshur** [comment]
This is done via #14 and #15, thanks to contributions by @shibukawa. :tada: There are only untested funcs left now (they print "not yet tested" to stderr), but all are implemented.

Thank you very much @shibukawa once again!

**Comment by shibukawa** [comment]
:+1:
